// @generated by scripts/codegen-factories.ts — do not edit. Source: @meonode/ui src/components/html.node.ts
//
// Sorted in byte order (Rust `str` `Ord`), which is guaranteed identical
// to JavaScript's default `Array.prototype.sort()` (UTF-16 code unit order)
// because every entry is a pure-ASCII JS identifier. See
// scripts/codegen-factories.ts for the full argument. `factory_children_first`
// relies on this invariant via `binary_search_by_key`; the sortedness unit
// test below is the enforcement point if that invariant is ever violated by
// a future regeneration.
//
// The bool is `children_first`: true when the factory was created via
// `createChildrenFirstNode` (props at call-site arg index 1, e.g.
// `P('text', { ... })`), false when created via `createNode` (props at arg
// index 0, e.g. `Div({ ... })`).
//
// `Node` itself is not in this table — it has its own call signature
// (`Node(element, props, deps)`, props at arg index 1) and is handled
// directly in the plugin's detection code.

pub static FACTORIES: &[(&str, bool)] = &[
    ("A", false),
    ("Abbr", true),
    ("Absolute", false),
    ("Address", false),
    ("Area", false),
    ("Article", false),
    ("Aside", false),
    ("Audio", false),
    ("B", true),
    ("Base", false),
    ("Bdi", true),
    ("Bdo", true),
    ("Blockquote", false),
    ("Body", false),
    ("Br", false),
    ("Button", true),
    ("Canvas", false),
    ("Caption", true),
    ("Center", false),
    ("Cite", true),
    ("Code", true),
    ("Col", false),
    ("Colgroup", false),
    ("Column", false),
    ("Container", false),
    ("Data", true),
    ("Datalist", false),
    ("Dd", false),
    ("Details", false),
    ("Dfn", true),
    ("Dialog", false),
    ("Div", false),
    ("Dl", false),
    ("Dt", false),
    ("Em", true),
    ("Embed", false),
    ("Fieldset", false),
    ("Figcaption", true),
    ("Figure", false),
    ("Fixed", false),
    ("Footer", false),
    ("Form", false),
    ("Grid", false),
    ("H1", true),
    ("H2", true),
    ("H3", true),
    ("H4", true),
    ("H5", true),
    ("H6", true),
    ("Head", false),
    ("Header", false),
    ("Hgroup", false),
    ("Hr", false),
    ("Html", false),
    ("I", true),
    ("Iframe", false),
    ("Img", false),
    ("Input", false),
    ("Kbd", true),
    ("Label", false),
    ("Legend", true),
    ("Li", false),
    ("Link", false),
    ("Main", false),
    ("MapElement", false),
    ("Mark", true),
    ("Menu", false),
    ("Meta", false),
    ("Meter", false),
    ("Nav", false),
    ("Noscript", false),
    ("ObjectElement", false),
    ("Ol", false),
    ("Optgroup", false),
    ("Option", true),
    ("Output", false),
    ("P", true),
    ("Param", false),
    ("Picture", false),
    ("Pre", true),
    ("Progress", false),
    ("Q", true),
    ("Relative", false),
    ("Root", false),
    ("Row", false),
    ("Rp", true),
    ("Rt", true),
    ("Ruby", false),
    ("S", true),
    ("Samp", true),
    ("Script", false),
    ("Search", false),
    ("Section", false),
    ("Select", false),
    ("Small", true),
    ("Source", false),
    ("Span", true),
    ("Static", false),
    ("Sticky", false),
    ("Strong", true),
    ("Style", false),
    ("Sub", true),
    ("Summary", true),
    ("Sup", true),
    ("Svg", false),
    ("SvgCircle", false),
    ("SvgDefs", false),
    ("SvgEllipse", false),
    ("SvgG", false),
    ("SvgLine", false),
    ("SvgLinearGradient", false),
    ("SvgPath", false),
    ("SvgPolygon", false),
    ("SvgPolyline", false),
    ("SvgRadialGradient", false),
    ("SvgRect", false),
    ("SvgStop", false),
    ("SvgSymbol", false),
    ("SvgText", false),
    ("SvgTspan", false),
    ("SvgUse", false),
    ("Table", false),
    ("Tbody", false),
    ("Td", false),
    ("Template", false),
    ("Text", true),
    ("Textarea", false),
    ("Tfoot", false),
    ("Th", false),
    ("Thead", false),
    ("Time", true),
    ("Title", true),
    ("Tr", false),
    ("Track", false),
    ("U", true),
    ("Ul", false),
    ("Var", true),
    ("Video", false),
    ("Wbr", false),
];

/// Returns `Some(children_first)` if `name` is a known @meonode/ui HTML
/// factory (e.g. `Div`, `P`, or an alias like `Container`/`Text`), where
/// `children_first` indicates whether the factory takes children as its
/// first argument (created via `createChildrenFirstNode`) rather than props
/// as its first argument (created via `createNode`). Returns `None` for
/// unrecognized names.
pub fn factory_children_first(name: &str) -> Option<bool> {
    FACTORIES
        .binary_search_by_key(&name, |(n, _)| *n)
        .ok()
        .map(|i| FACTORIES[i].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn factories_is_sorted() {
        assert!(
            FACTORIES.windows(2).all(|w| w[0].0 < w[1].0),
            "FACTORIES must be strictly sorted by name (byte order) for binary_search_by_key to work"
        );
    }

    #[test]
    fn recognizes_plain_factory() {
        assert_eq!(factory_children_first("Div"), Some(false));
    }

    #[test]
    fn recognizes_children_first_factory() {
        assert_eq!(factory_children_first("P"), Some(true));
    }

    #[test]
    fn recognizes_children_first_alias() {
        assert_eq!(factory_children_first("Text"), Some(true));
    }

    #[test]
    fn recognizes_plain_alias() {
        assert_eq!(factory_children_first("Container"), Some(false));
    }

    #[test]
    fn rejects_unknown_name() {
        assert_eq!(factory_children_first("NotARealFactory"), None);
    }
}
