#!/usr/bin/env bun
/**
 * Codegen: parses @meonode/ui's `src/components/html.node.ts` for factory
 * declarations and emits crates/meonode-swc-plugin/src/factories.rs.
 *
 * Source of truth: the literal `export const X = createNode(...)` /
 * `export const X = createChildrenFirstNode(...)` declarations in that file,
 * plus simple alias re-exports (`export const A = B`). This is a syntactic
 * parse (line-anchored regex), not a TS compile — it deliberately does NOT
 * execute any code in the @meonode/ui checkout, unlike codegen-css-set.ts,
 * because the factory list is fully determined by which creator function
 * (`createNode` vs `createChildrenFirstNode`) each export's declaration line
 * starts with.
 *
 * The `Node` factory itself is intentionally excluded from the generated
 * list — it has a different call signature (`Node(element, props, deps)`,
 * props at arg index 1) and is handled directly in the plugin's detection
 * code, not via this table.
 *
 * Usage:
 *   bun run scripts/codegen-factories.ts
 *   MEONODE_UI_DIR=/path/to/ui bun run scripts/codegen-factories.ts
 *
 * Env:
 *   MEONODE_UI_DIR  Path to the @meonode/ui checkout (default: "../ui",
 *                   relative to this repo's root).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_PATH = join(REPO_ROOT, "crates/meonode-swc-plugin/src/factories.rs");

// Matches the opening line of a factory declaration, e.g.:
//   export const Div = createNode('div')
//   export const Root = createNode('div', {
//   export const P = createChildrenFirstNode('p')
const CREATOR_LINE_RE =
  /^export const ([A-Za-z_$][A-Za-z0-9_$]*) = (createNode|createChildrenFirstNode)\(/;

// Matches a bare alias re-export, e.g.:
//   export const Container = Div
//   export const Text = P
const ALIAS_LINE_RE =
  /^export const ([A-Za-z_$][A-Za-z0-9_$]*) = ([A-Za-z_$][A-Za-z0-9_$]*)$/;

function main() {
  const uiDir = resolve(REPO_ROOT, process.env.MEONODE_UI_DIR ?? "../ui");
  const srcPath = join(uiDir, "src/components/html.node.ts");

  let text: string;
  try {
    text = readFileSync(srcPath, "utf8");
  } catch (err) {
    throw new Error(
      `Failed to read ${srcPath}: ${(err as Error).message}. Set MEONODE_UI_DIR to point at a valid @meonode/ui checkout.`,
    );
  }

  const factories = new Map<string, boolean>(); // name -> children_first

  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();

    const creatorMatch = CREATOR_LINE_RE.exec(line);
    if (creatorMatch) {
      const [, name, creator] = creatorMatch;
      factories.set(name, creator === "createChildrenFirstNode");
      continue;
    }

    const aliasMatch = ALIAS_LINE_RE.exec(line);
    if (aliasMatch) {
      const [, alias, target] = aliasMatch;
      if (factories.has(target)) {
        factories.set(alias, factories.get(target)!);
      }
    }
  }

  if (factories.size === 0) {
    throw new Error(
      `No factory declarations found in ${srcPath}. Expected lines like \`export const Div = createNode('div')\`.`,
    );
  }

  // Sort-order verification (see scripts/codegen-css-set.ts for the full
  // argument): Rust `&[&str]::binary_search` orders by byte order, which is
  // identical to JS default `Array.prototype.sort()` only for pure-ASCII
  // strings. Factory names are JS identifiers (`[A-Za-z_$][A-Za-z0-9_$]*`),
  // always ASCII, so we assert that here rather than merely assuming it.
  for (const name of factories.keys()) {
    if (!/^[\x00-\x7f]*$/.test(name)) {
      throw new Error(
        `Non-ASCII factory name encountered: ${JSON.stringify(name)}. ` +
          "JS UTF-16 sort order and Rust byte order are no longer " +
          "guaranteed to match; codegen aborted.",
      );
    }
  }

  const sortedNames = [...factories.keys()].sort();
  for (let i = 1; i < sortedNames.length; i++) {
    if (!(sortedNames[i - 1] < sortedNames[i])) {
      throw new Error(
        `Sort invariant violated at index ${i}: ${JSON.stringify(sortedNames[i - 1])} >= ${JSON.stringify(sortedNames[i])}`,
      );
    }
  }

  const rustFile = renderRust(sortedNames.map((name) => [name, factories.get(name)!] as const));

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, rustFile, "utf8");

  console.log(
    `Wrote ${sortedNames.length} factory entries to ${OUT_PATH.replace(REPO_ROOT + "/", "")}`,
  );
}

function renderRust(entries: readonly (readonly [string, boolean])[]): string {
  const rows = entries
    .map(([name, childrenFirst]) => `    (${JSON.stringify(name)}, ${childrenFirst}),`)
    .join("\n");

  return `// @generated by scripts/codegen-factories.ts — do not edit. Source: @meonode/ui src/components/html.node.ts
//
// Sorted in byte order (Rust \`str\` \`Ord\`), which is guaranteed identical
// to JavaScript's default \`Array.prototype.sort()\` (UTF-16 code unit order)
// because every entry is a pure-ASCII JS identifier. See
// scripts/codegen-factories.ts for the full argument. \`factory_children_first\`
// relies on this invariant via \`binary_search_by_key\`; the sortedness unit
// test below is the enforcement point if that invariant is ever violated by
// a future regeneration.
//
// The bool is \`children_first\`: true when the factory was created via
// \`createChildrenFirstNode\` (props at call-site arg index 1, e.g.
// \`P('text', { ... })\`), false when created via \`createNode\` (props at arg
// index 0, e.g. \`Div({ ... })\`).
//
// \`Node\` itself is not in this table — it has its own call signature
// (\`Node(element, props, deps)\`, props at arg index 1) and is handled
// directly in the plugin's detection code.

pub static FACTORIES: &[(&str, bool)] = &[
${rows}
];

/// Returns \`Some(children_first)\` if \`name\` is a known @meonode/ui HTML
/// factory (e.g. \`Div\`, \`P\`, or an alias like \`Container\`/\`Text\`), where
/// \`children_first\` indicates whether the factory takes children as its
/// first argument (created via \`createChildrenFirstNode\`) rather than props
/// as its first argument (created via \`createNode\`). Returns \`None\` for
/// unrecognized names.
pub fn factory_children_first(name: &str) -> Option<bool> {
    FACTORIES
        .binary_search_by_key(&name, |(n, _)| *n)
        .ok()
        .map(|i| FACTORIES[i].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn factories_is_sorted() {
        assert!(
            FACTORIES.windows(2).all(|w| w[0].0 < w[1].0),
            "FACTORIES must be strictly sorted by name (byte order) for binary_search_by_key to work"
        );
    }

    #[test]
    fn recognizes_plain_factory() {
        assert_eq!(factory_children_first("Div"), Some(false));
    }

    #[test]
    fn recognizes_children_first_factory() {
        assert_eq!(factory_children_first("P"), Some(true));
    }

    #[test]
    fn recognizes_children_first_alias() {
        assert_eq!(factory_children_first("Text"), Some(true));
    }

    #[test]
    fn recognizes_plain_alias() {
        assert_eq!(factory_children_first("Container"), Some(false));
    }

    #[test]
    fn rejects_unknown_name() {
        assert_eq!(factory_children_first("NotARealFactory"), None);
    }
}
`;
}

main();
